### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by karakayasemi** [ITUBIDB/cavabunga-server#23]
We should somehow document API endpoints. Swagger looks like a good option to consider for this purpose.

**Comment by karakayasemi** [comment]
Hi, I'm [GitMate.io](https://gitmate.io)!

It seems you've just enabled the issue triaging. I'm just scraping all issues from your repository and will give you some more information about this in a few minutes or so.

Because of the rate limit we can't scrape all information (including all comments and authors) right now - our system is already set up to scrape this in the next days over which the predictions will become more precise every day.

If you want me to use a different account for triaging your issues, simply create one and log in with it.

**Sit tight!**

**Comment by dgkncelik** [comment]
0bbd7df0ced9da428af7d7dc39842fb147193bca

**Comment by karakayasemi** [comment]
Commit looks okay, is it ready for Pull Request? If it is not finished yet, you can open by putting WIP label.

**Comment by karakayasemi** [comment]
resolved #30
