### ISSUE TITLE
Validatation

### ISSUE THREAD

**Issue by dgkncelik** [ITUBIDB/cavabunga-server#28]
we referenced ical data format for out object format, so we need some verification mechanism for components, parameters and properties. 
For example:
* we cannot have event more then 2 nested components (e.g. cannot have event object in alarm object calendar->event->alarm is ok but calendar->event->alarm->event is not ok). 
* we need data verification for parameters and properties: as rest api accepts string but we need the check if its correct or not.

**Comment by dgkncelik** [comment]
new branch for that issue 
https://github.com/ITUBIDB/cavabunga-core/commits/development

**Comment by karakayasemi** [comment]
please give PR with WIP label. In this way, we can discuss something on open PR.

**Comment by dgkncelik** [comment]
https://github.com/ITUBIDB/cavabunga-core/pull/32
